// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/25/2026, 1:27:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/plugins/**/*.{js,ts,mjs}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/composables/**/*.{js,ts,mjs}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/utils/**/*.{js,ts,mjs}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ade-ridwan/Documents/1. PROJECT/Personal/Project/Tzinghua/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;